version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Specify the Node.js version you want to use
    commands:
      - echo "Installing dependencies..."
      - npm install # Install npm dependencies

  pre_build:
    commands:
      - echo "Building the React app..."
      - npm run build # Build the React app

  build:
    commands:
      - echo "Copying build files to S3..."
      - aws s3 sync build/ s3://ball-app

artifacts:
  files:
    - '**/*'
  base-directory: build
